[package]
name = "rebox"
version = "0.1.0"
edition = "2024"

[dependencies]
boxutils = { path = "./utils" }
coreutils = { path = "./coreutils" }
shell = { path = "./shell" }


[[bin]]
name = "box"
path = "./src/main.rs"
